spring:
  application:
    name: gameVault

  datasource:
    url: jdbc:postgresql://localhost:5433/gamevault
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

gamevault:
  security:
    secret: "palavra-secreta"